### ISSUE TITLE
Support for Speedtest Custom (the Replacement for Speedtest Mini)

### ISSUE THREAD

**Issue by ChMG** [sivel/speedtest#3]
Now that speedtest mini has been deprecated in favor of speedtest custom, I am searching for a comand line tool for this.

Unfortunately, the server id's of the private speedtestcustom servers are not in the public server list.
The server data is located in a script tag inside the html header of the customized test website.

Is it possible to integrate it in this tool?

**Comment by RERobbins** [comment]
I have been wondering the same thing.

**Comment by sivel** [comment]
I have no plans to add this functionality to speedtest-cli at this time. speedtest-cli will continue to only support the legacy http tests.
