### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by bilbilivo** [sivel/speedtest#6]
Getting "x509: certificate has expired or is not yet valid" when running the code.

./speedtest_linux_386 -version
0.0.2

./speedtest_linux_386
Retrieving speedtest.net configuration...
Error retrieving Speedtest.net configuration: Get https://www.speedtest.net/speedtest-config.php: x509: certificate has expired or is not yet valid.

**Comment by sivel** [comment]
This indicates one of a few things.  The cert for www.speedtest.net is invalid, or your local cacerts need to be updated.

Neither of which do I have control over.
